apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-zurich-simulator-machine-status
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-validation
    format:
      type: json
    next:
    - stage-processing
    partitionCount: 1
    partitionStrategy:
      expression: .topic
      type: key
    qos: 1
    topics:
    - zurich/opcua-simulator
    type: input/mqtt@v1
  stages:
    stage-processing:
      displayName: stage-processing
      expression: '.payload = [(.payload | .[] | .Payload |= with_entries (
          if (.key | test("Status") | not) then .
          elif .value.Value < 30 then (.key += ".Mode1" | .value.Value = true)
          elif .value.Value < 60 then (.key += ".Mode2"  | .value.Value = true )
          elif .value.Value < 70 then (.key += ".Fault" | .value.Value = true )
          elif .value.Value < 80 then (.key += ".Idle" | .value.Value = true )
          else (.key += ".Undefined" | .value.Value = true ) end 
        ))]'
      next:
      - output
      type: processor/transform@v1
    output:
      authentication:
        type: serviceAccountToken
      broker: tls://aio-mq-dmqtt-frontend:8883
      displayName: mq-output-validation-filtering
      format:
        path: .payload
        type: json
      qos: 1
      topic:
        type: static
        value: "zurich/opcua"
      type: output/mqtt@v1
      userProperties: []