apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-preprocess-opcua-payload
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-validation
    format:
      type: json
    next:
    - stage-processing
    partitionCount: 1
    partitionStrategy:
      expression: .topic
      type: key
    qos: 1
    topics:
    - zurich/opcua
    type: input/mqtt@v1
  stages:
    stage-processing:
      displayName: stage-processing
      expression: '.payload | .[] | to_entries | map( { ( .key | ((.[0:1] | ascii_downcase) + .[1:] ) ): .value } ) | add'
      next:
      - output
      type: processor/transform@v1
    output:
      authentication:
        type: serviceAccountToken
      broker: tls://aio-mq-dmqtt-frontend:8883
      displayName: mq-output-validation-filtering
      format:
        path: .
        type: json
      qos: 1
      topic:
        type: static
        value: "zurich/input"
      type: output/mqtt@v1
      userProperties: []