apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-metrics-to-grafana
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-validation
    format:
      type: json
    next:
    - stage-payload
    partitionCount: 1
    partitionStrategy:
      expression: .topic
      type: key
    qos: 1
    topics:
    - metrics/aio/machine-status
    - metrics/aio/total-count
    type: input/mqtt@v1
  stages:
    stage-payload:
      displayName: stage-payload
      expression: ' . + (.request =
          {
            "resourceMetrics": [
            {
                "resource": {
                    "attributes": [
                        {
                            "key": "plant.id",
                            "value": {
                                "stringValue": .payload.PlantId
                            }
                        },
                        {
                            "key": "line.id",
                            "value": {
                                "stringValue": .payload.LineId
                            }
                        },
                        {
                            "key": "machine.id",
                            "value": {
                                "stringValue": .payload.MachineId
                            }
                        }
                    ]
                },
                "scopeMetrics": [
                    {
                        "scope": {
                          "name": "aio-data-processing-pipeline"
                        },
                        "metrics": [
                            {
                                "name": (":" + .payload.VariableId),
                                "unit": "1",
                                "description": .payload.VariableId,
                                "gauge": {
                                    "dataPoints": [
                                        {
                                            "asInt": (
                                              if .payload.Value == "FAULT" then 400
                                              elif .payload.Value == "IDLE" then 200
                                              elif .payload.Value == "MODE1" then 101
                                              elif .payload.Value == "MODE2" then 102
                                              elif .payload.Value == "UNDEFINED" then 0
                                              else .payload.Value | tonumber
                                              end
                                            ),
                                            "timeUnixNano": (now | . * 1000000000)
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }]
        })'
      next:
      - send-metrics-to-otlc
      type: processor/transform@v1
    send-metrics-to-otlc:
      displayName: send-metrics-to-otlc
      next:
      - output
      type: processor/http@v1
      url: http://aio-otel-collector.azure-iot-operations.svc.cluster.local:4318/v1/metrics
      authentication:
        type: none
      method: POST
      request:
        headers:
          - key:
              type: static
              value: Accept
            value:
              type: static
              value: application/json
          - key:
              type: static
              value: Content-Type
            value:
              type: static
              value: application/json
        body:
          type: json
          path: .request
      response:
        body:
          path: .response
          type: raw
      description: Send metrics to OpenTelemetry Collector
    output:
      authentication:
        type: serviceAccountToken
      broker: tls://aio-mq-dmqtt-frontend:8883
      displayName: mq-output-validation-filtering
      format:
        path: .
        type: json
      qos: 1
      topic:
        type: static
        value: metrics/aio/debug
      type: output/mqtt@v1
      userProperties: []
    