apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-current-shift-counts
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-zurich
    format:
      type: json
    next:
    - transform-input
    partitionCount: 1
    partitionStrategy:
      expression: .payload.payload | keys[0] as $k | if $k | test("Status|Counter") then 
                                                        ($k | split(".")[1])
                                                     else .topic end
      type: key
    qos: 1
    topics:
    - zurich/input/valid
    type: input/mqtt@v1
  stages:
    transform-input:
      description: Transforms node object to nodeid and counter keeping lkv values
      displayName: transform-input
      expression: '.payload = (
          .payload.payload | to_entries | map(if .key | test("Counter") then {"key": "NodeId", "value": .key},
          {"key": (.key | split(".")[-1]), "value": .value.Value},
          {"key": "MachineId", "value": (.key | split(".")[1])}
          else
          .
          end) | from_entries)'
      next:
      - filter-leave-counter-tag
      type: processor/transform@v1
    filter-leave-counter-tag:
      displayName: filter-leave-counter-tag
      expression: (.payload.NodeId != null) and (.payload.NodeId | test("Counter"))
      next:
      - lkv
      type: processor/filter@v1
    lkv:
      displayName: lkv-good-bad-counter
      next:
      - filter
      properties:
      - inputPath: .payload.GoodCounter
        outputPath: .payload.lkvGoodCounter
      - inputPath: .payload.BadCounter
        outputPath: .payload.lkvBadCounter
      type: processor/lkv@v1
    filter:
      displayName: filter-zeroes
      expression: ((.payload.GoodCounter != 0) and (.payload.GoodCounter != null)) or ((.payload.BadCounter != 0) and (.payload.BadCounter != null))
      next:
      - calculate-total
      type: processor/filter@v1
    calculate-total:
      description: Calculates the current shift count
      displayName: calculate-current-shift-total
      expression: '.payload = (.payload | { "NodeId": .NodeId, 
                                            "CurrentShiftCounter": (if has ("GoodCounter") then
                                                                      (.GoodCounter + .lkvBadCounter)
                                                                    elif has("BadCounter") then 
                                                                      (.BadCounter + .lkvGoodCounter)
                                                                    else 0 end), 
                                            "MachineId": .MachineId})'
      next:
      - output
      type: processor/transform@v1
    output:
      authentication:
        type: serviceAccountToken
      broker: tls://aio-mq-dmqtt-frontend:8883
      displayName: mq-output-zurich-current-shift-total
      format:
        path: .payload
        type: json
      qos: 1
      topic:
        type: static
        value: zurich/current-shift-total
      type: output/mqtt@v1
      userProperties: []