apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-refdata-list
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-list-refdata
    format:
      type: json
    next:
    - passthrough
    partitionCount: 1
    partitionStrategy:
      expression: .topic
      type: key
    qos: 1
    topics:
    - list-refdata
    type: input/mqtt@v1
  stages:
    passthrough:
      alwaysArray: false
      conditions: []
      dataset: dataset-reference-data
      displayName: Add reference data
      limit: 100
      next:
      - output
      outputPath: .payload.refdata
      type: processor/enrich@v1
    output:
      authentication:
        type: serviceAccountToken
      broker: tls://aio-mq-dmqtt-frontend:8883
      displayName: mq-output-refdata
      format:
        path: .payload
        type: json
      qos: 1
      topic:
        type: static
        value: list-refdata-output
      type: output/mqtt@v1
      userProperties: []
