apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-shift-history-list
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-list-shift-history
    format:
      type: json
    next:
    - passthrough
    partitionCount: 1
    partitionStrategy:
      expression: .topic
      type: key
    qos: 1
    topics:
    - list-shifts
    type: input/mqtt@v1
  stages:
    passthrough:
      alwaysArray: false
      conditions: []
      dataset: dataset-shift-history-totals
      displayName: Add shift history
      limit: 100
      next:
      - output
      outputPath: .payload.shifts
      type: processor/enrich@v1
    output:
      authentication:
        type: serviceAccountToken
      broker: tls://aio-mq-dmqtt-frontend:8883
      displayName: mq-output-shifts
      format:
        path: .payload
        type: json
      qos: 1
      topic:
        type: static
        value: list-shifts-output
      type: output/mqtt@v1
      userProperties: []
