apiVersion: dataprocessor.iotoperations.azure.com/v1
kind: Pipeline
metadata:
  name: pipeline-shift-history-totals-load-manual
  namespace: azure-iot-operations
spec:
  enabled: true
  input:
    authentication:
      type: serviceAccountToken
    broker: tls://aio-mq-dmqtt-frontend:8883
    cleanSession: false
    displayName: mq-input-reference-data
    format:
      type: json
    next:
    - output
    partitionCount: 1
    partitionStrategy:
      expression: .topic
      type: key
    qos: 1
    topics:
    - shift-history
    type: input/mqtt@v1
  stages:
    output:
      dataset: dataset-shift-history-totals
      displayName: refdataset-output-shift-history-totals
      type: output/refdata@v1
