{
 "title": "Total Count and Machine Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(plant_id, line_id) (:total_count)",
     "legendFormat": "{{plant_id}}/{{line_id}}"
    }
   ]
  },
  {
   "title": "Last Total Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(plant_id) (:total_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machine Status",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": ":machine_status",
     "legendFormat": "{{plant_id}}/{{line_id}}/{{machine_id}}"
    }
   ]
  }
 ]
}