---
apiVersion: v1
kind: Pod
metadata:
  name: mqtt-client
  namespace: azure-iot-operations
spec:
  containers:
    - name: mqtt-client
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args:
        ["apt-get update && apt-get -y install mosquitto-clients && sleep 30d"]
      imagePullPolicy: IfNotPresent
