---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: azure-iot-operations
  name: simulator-conf
data:
  config.yml: |-
    metrics:
      type: prometheus
      port: 2114
    logLevel: 0
    simulation:
      target:
        host: aio-mq-dmqtt-frontend
        port: 1883
      sites:
        - name: 2
          mqttVersion: v5
          assetCount: 1
          tags:
            - id: Good
              idTemplate: "ns=%s;s=AreaName.MachineName.Counter.%s"
              configuration: rand(x*4-4, x*4)
              count: 1
            - id: Status
              idTemplate: "ns=%s;s=AreaName.MachineName.%s"
              configuration: rand(0, 99)
              count: 1
          rate:
            messagesPerPeriod: 1
            periodSeconds: 5
            tagsPerMessage: 1
          payloadFormat: OPCUA
          topicFormat: zurich/opcua-simulator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azure-iot-operations
  name: data-simulator
  labels:
    app: data-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-simulator
  template:
    metadata:
      labels:
        app: data-simulator
    spec:
      containers:
        - name: data-simulator
          image: ghcr.io/Azure-Samples/explore-iot-operations/industrial-data-simulator:latest
          imagePullPolicy: Always
          ports:
            - name: prometheus
              containerPort: 2114
          resources:
            requests:
              memory: "128Mi"
              cpu: "1000m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          command:
            - "./bin/industrial-data-simulator"
            - "--stdin=false"
            - "--config=/etc/data-simulator/config.yml"
          volumeMounts:
            - mountPath: /etc/data-simulator/config.yml
              subPath: config.yml
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: simulator-conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: azure-iot-operations
  name: simulator-svc-prom
  labels:
    app: data-simulator
spec:
  ports:
    - port: 2114
      name: prometheus
  type: ClusterIP
  selector:
    app: data-simulator
---
apiVersion: mq.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: data-simulator-listener-counter
  namespace: azure-iot-operations
spec:
  authenticationEnabled: false
  authorizationEnabled: false
  brokerRef: broker
  port: 1883
  serviceName: aio-mq-dmqtt-frontend
  serviceType: clusterIp
